import { Connection, PublicKey } from "@solana/web3.js";
import { db } from "./db.js";
import { env } from "./env.js";

const WSOL = "So11111111111111111111111111111111111111112";
const PUMPFUN_SUPPLY = 1_000_000_000; // standard pump.fun total supply (UI units)

function pct(sorted: number[], p: number): number {
  if (sorted.length === 0) return 0;
  const idx = Math.min(sorted.length - 1, Math.max(0, Math.floor((p / 100) * sorted.length)));
  return sorted[idx]!;
}

async function main() {
  const { data, error } = await (db as any)
    .from("custody_journey_wallets")
    .select("wallet,last_tx_sig,token_mint,total_unresolved_outflow_tokens")
    .eq("hop_depth", 2)
    .gt("total_unresolved_outflow_tokens", 0)
    .not("last_tx_sig", "is", null)
    .order("total_unresolved_outflow_tokens", { ascending: false })
    .limit(60);
  if (error) throw new Error(`query failed: ${error.message}`);

  const rows = (Array.isArray(data) ? data : []).filter(
    (r: { last_tx_sig?: string; token_mint?: string }) =>
      String(r.last_tx_sig ?? "").length > 40 && String(r.token_mint ?? "").length > 30,
  );
  console.log(`Estimating market cap at dump across ${rows.length} dumps (approximate)...\n`);

  const conn = new Connection(env.RPC_URL, "confirmed");
  const mcapsSol: number[] = [];
  let ok = 0;

  for (const row of rows) {
    const mint = String(row.token_mint);
    const sig = String(row.last_tx_sig);
    const soldTokens = Number(row.total_unresolved_outflow_tokens);
    if (!(soldTokens > 0)) continue;
    try {
      const tx = await conn.getParsedTransaction(sig, { maxSupportedTransactionVersion: 0, commitment: "confirmed" });
      if (!tx || !tx.meta) continue;

      // SOL generated by the sale ≈ the largest positive WSOL owner-delta in the tx,
      // else the largest positive native SOL delta among accounts.
      const preT = (tx.meta.preTokenBalances ?? []) as Array<{ owner?: string; mint?: string; uiTokenAmount?: { uiAmount?: number } }>;
      const postT = (tx.meta.postTokenBalances ?? []) as Array<{ owner?: string; mint?: string; uiTokenAmount?: { uiAmount?: number } }>;
      const wsolDelta = new Map<string, number>();
      for (const b of postT) if (b.mint === WSOL && b.owner) wsolDelta.set(b.owner, (wsolDelta.get(b.owner) ?? 0) + (b.uiTokenAmount?.uiAmount ?? 0));
      for (const b of preT) if (b.mint === WSOL && b.owner) wsolDelta.set(b.owner, (wsolDelta.get(b.owner) ?? 0) - (b.uiTokenAmount?.uiAmount ?? 0));
      let solOut = 0;
      for (const d of wsolDelta.values()) if (d > solOut) solOut = d;
      if (solOut <= 0) {
        const keys = tx.transaction.message.accountKeys as Array<{ pubkey: PublicKey }>;
        const pre = tx.meta.preBalances ?? [];
        const post = tx.meta.postBalances ?? [];
        for (let i = 0; i < keys.length; i++) {
          const d = ((post[i] ?? 0) - (pre[i] ?? 0)) / 1e9;
          if (d > solOut) solOut = d;
        }
      }
      if (solOut <= 0.0001) continue;

      const pricePerToken = solOut / soldTokens; // SOL per token at dump
      const mcapSol = pricePerToken * PUMPFUN_SUPPLY;
      if (mcapSol > 0 && Number.isFinite(mcapSol)) {
        mcapsSol.push(mcapSol);
        ok += 1;
        console.log(`  ${mint.slice(0,8)}  sold ${soldTokens.toExponential(2)} tok  for ~${solOut.toFixed(3)} SOL  =>  mcap ~${mcapSol.toFixed(1)} SOL`);
      }
    } catch { /* skip */ }
    await new Promise((r) => setTimeout(r, 180));
  }

  mcapsSol.sort((a, b) => a - b);
  console.log(`\n=== MARKET CAP AT DUMP (SOL) — ${ok} dumps ===`);
  console.log(`  p10 : ${pct(mcapsSol,10).toFixed(1)} SOL`);
  console.log(`  p25 : ${pct(mcapsSol,25).toFixed(1)} SOL`);
  console.log(`  median: ${pct(mcapsSol,50).toFixed(1)} SOL`);
  console.log(`  p75 : ${pct(mcapsSol,75).toFixed(1)} SOL`);
  console.log(`  p90 : ${pct(mcapsSol,90).toFixed(1)} SOL`);
  const inBand = mcapsSol.filter((m) => m >= pct(mcapsSol,25) && m <= pct(mcapsSol,75)).length;
  console.log(`\nIf p25–p75 is a TIGHT band, that band is his sell-threshold market cap.`);
  console.log(`(Rough USD: multiply SOL figures by the SOL price, ~$200.) ${inBand}/${ok} dumps fall in the middle band.`);
}

main().then(() => process.exit(0), (err) => { console.error(err instanceof Error ? err.message : String(err)); process.exit(1); });
